# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_cover_image_examplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='image',
            field=models.ImageField(default='media/no-img.jpg', upload_to='.'),
        ),
    ]
