# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170328_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='image',
            new_name='model_pic',
        ),
    ]
