# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170328_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(default='media/no-img.jpg', upload_to=''),
        ),
    ]
