# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20170620_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
